name: flame_game_demo
description: A Flutter + Flame v09 game demo with main menu and pause/resume system.
publish_to: 'none'
version: 1.0.0+9

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.32.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/player.png
    - assets/images/obstacle.png
    - assets/images/powerup.png
