name: flame_game_demo
description: A Flutter + Flame game demo with lives, power-ups, and game over screen.
publish_to: 'none'
version: 1.0.0+8

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.32.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/player.png
    - assets/images/obstacle.png
    - assets/images/powerup.png
