name: flame_game_demo
description: A Flutter + Flame v12 game with audio (BGM + SFX), bosses, levels, power-ups, pause, and web support.
publish_to: 'none'
version: 1.0.0+12

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.32.0
  flame_audio: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/player.png
    - assets/images/obstacle.png
    - assets/images/powerup.png
    - assets/images/boss.png
    - assets/audio/bgm.wav
    - assets/audio/hit.wav
    - assets/audio/powerup.wav
    - assets/audio/boss_down.wav
