name: flame_game_demo
description: A Flutter + Flame v11 game with boss fights, levels, power-ups, pause, and web support.
publish_to: 'none'
version: 1.0.0+11

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.32.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/player.png
    - assets/images/obstacle.png
    - assets/images/powerup.png
    - assets/images/boss.png
